### ISSUE TITLE
There are too few examples of pipeline agent about dockerfile

### ISSUE THREAD

**Issue by chinakevinguo** [docker/jenkins-pipeline-scripts#20]
There are too few examples of pipeline agent about dockerfile in documentation

When used the dockerfile to build image ,even do not know how to specify image name,or tag

```pipeline {
  agent {
    dockerfile  {
      args '-v /tmp:/tmp'
      additionalBuildArgs '-t alpine:3.6'
    }
  }
  stages {
    stage('example build') {
      steps {
        echo 'Hello'
      }
    }
  }
}```

i have the below error

```
java.io.IOException: Failed to run image '5d3282411bf84673eb3eb57dd0461902d9fb5854'. Error: /usr/bin/docker-current: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"cat\\\": executable file not found in $PATH\"\n".
```

**Comment by zarcha** [comment]
Im having issues with this as well

**Comment by psftw** [comment]
This repository contains some (since deprecated) scripting library functions, and is not the appropriate place for Q&A on the underlying syntax. Docker does not directly maintain any of the docker-related plugins either. The upstream docs have come a long way in recent years: https://jenkins.io/doc/book/pipeline/syntax/
