### ISSUE TITLE
How is your Jenkins 'master' configured for SSH push in the Jenkinsfile?

### ISSUE THREAD

**Issue by mkobit** [docker/jenkins-pipeline-scripts#5]
I just came across this repository and was looking to take some of the useful parts from it. I saw in the `Jenkinsfile` that there is a section for pushing to the `workflowLibs.git`:

``` groovy
sh "git push jenkins@localhost:workflowLibs.git '+refs/remotes/origin/*:refs/heads/*'"
```

I was trying this locally and was getting:

```
+ git push jenkins@localhost:workflowLibs.git '+refs/remotes/origin/*:refs/heads/*'
Host key verification failed.
fatal: Could not read from remote repository.
```

I am using a different SSH key to pull with the `checkout scm`, but I'm wondering how you have configured your Jenkins to allow for the `git push` to succeed?

**Comment by runelabs** [comment]
This "simplified" URL using `jenkins@localhost` is similar to `ssh://jenkins@localhost:22/workflowLibs.git`.

Running the Jenkins built-in SSH/Git Server on a fixed port 22 is a privileged capability.
When you need to run the SSHD on a privileged port (lower than 1000), this can be done by granting CAP_NET_BIND_SERVICE to the jenkins-running user and file/process. (see e.g docker/docker#8460 )

I also wanted to replicate this way of checking in the Jenkins global pipeline scripts, and I was able to do this by first having:
- a "jenkins" user for the Jenkins CLI - in https://yourjenkins/asynchPeople - which must have it's "SSH Public Key" set - https://yourjenkins/user/jenkins/configure (password is not used when doing the SSH key access method)

Then there are some variants to the needed master jenkins SSH configuration...

File-based SSH-keys:
- `/var/jenkinshome/.ssh/id_rsa`   - and `id_rsa.pub` (same as "jenkins" user SSH Public Key).

This way the authentication is done in the "sh" pipeline step through looking up the "id_rsa" and matching it with the "jenkins" CLI user.

Jenkins SSH credentials secret embedded:
- having a SSH-credentials entry with the SSH private key entered directly.
- wrapping the "sh" pipeline step with `sshagent(credentials: ['jenkinslocalssh']) { ... }`.

This avoids having the private key on the file-system in plain form, but offers no real security improvement since the Jenkins credentials encryption secrets are all available from /var/jenkinshome/ anyways.

Jenkins SSH credentials secret from file:
- e.g reading from `~/.ssh` - i.e `/var/jenkinshome/.ssh/id_rsa`.
- same wrapping step as credentials entry above.

This is basically the same as above - only in addition enabling using the SSH credentials with `sshagent` wrappers.

Any "sh" pipeline step running on the Jenkins "master" that are not wrapped with credentials would use the `~/.ssh/config` as well, so you could further configure like normal SSH use for users, hosts, identityfiles, proxies etc.

The `/var/jenkinshome/.ssh/authorized_keys` does not affect any of the pipeline steps or the Jenkins built-in SSHD/Git Server.

So, if you have `/var/jenkinshome/.ssh/config` as follows:

```
Host localhost
  User jenkins
  Port 2222
  IdentityFile ~/.ssh/id_rsa
```

Then you could do your "sh" steps as such:

```
 node("master") {
   sh """
       ssh localhost who-am-i
       ssh localhost help
       ssh localhost help who-am-i
       git clone localhost:workflowLibs.git
       ...
   """
```

For more on the Jenkins CLI built-in commands and making your own CLI commands as well - see:
- http://javadoc.jenkins-ci.org/hudson/cli/CLICommand.html
- https://wiki.jenkins-ci.org/display/JENKINS/Writing+CLI+commands

**Comment by runelabs** [comment]
Pulling to the directory is seemingly also possible:
- https://issues.jenkins-ci.org/browse/JENKINS-34476

**Comment by mkobit** [comment]
Our current setup is a little bit wonky in that we configured the `workflowLibs.git` directory to point to our remote. We did some SSH configuration We then have a weird redirection for running a job on the master with a `git pull`, but we definitely are not happy with the current state. It's not in a very reproducible state so I was exploring other options.

Thanks for the detailed description! It is very helpful

**Comment by j-ibarra** [comment]
My solution
``
Install [SSH Agent Plugin](https://plugins.jenkins.io/ssh-agent)

![Captura de pantalla de 2019-07-04 10-52-34](https://user-images.githubusercontent.com/4218738/60675241-e13a3400-9e49-11e9-9f41-6ee2f9daf77a.png)

using GIT_SSH to set credentials **jenkins-generated-ssh-key**

>            steps {
>                sshagent (credentials: ['jenkins-generated-ssh-key']) {
>                     sh("""
>                         git tag ${props['DATE_TAG']}
>                         git push --tags
>                     """)
>                 }
>             }
